#!/bin/bash

set -e

juju-log "installing HyperDex"
sudo wget -O - http://ubuntu.hyperdex.org/hyperdex.gpg.key | apt-key add -
sudo wget -O /etc/apt/sources.list.d/hyperdex.list http://ubuntu.hyperdex.org/precise.list
sudo apt-get update
sudo apt-get install hyperdex
