#!/bin/bash

set -e

juju-log "installing HyperDex"

sudo groupadd -r hyperdex || juju-log "group \"hyperdex\" already exists"
sudo useradd -g hyperdex -m -r hyperdex || juju-log "user \"hyperdex\" already exists"
sudo -u hyperdex mkdir -p /home/hyperdex/coordinator/logs
sudo -u hyperdex mkdir -p /home/hyperdex/coordinator/data
sudo -u hyperdex mkdir -p /home/hyperdex/daemon/logs
sudo -u hyperdex mkdir -p /home/hyperdex/daemon/data

sudo wget -O - http://ubuntu.hyperdex.org/hyperdex.gpg.key | apt-key add -
sudo wget -O /etc/apt/sources.list.d/hyperdex.list http://ubuntu.hyperdex.org/precise.list
sudo apt-get update -y
sudo apt-get install -y hyperdex hyperdex-coordinator hyperdex-daemon hyperdex-tools python-hyperdex-client python-hyperdex-admin
